name: flutter_cnblog
description: A Flutter project of cnblog client.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.7+10

environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.0.0
  retrofit: ^4.0.1
  logger: ^2.0.2+1
  json_annotation: ^4.6.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.2.1
  timeago: ^3.2.2
  double_back_to_close: ^2.0.0
  badges: ^3.0.2
  animations: ^2.0.3
  shimmer: ^3.0.0
  flutter_native_splash: ^2.2.7
  flutter_inappwebview: ^5.4.3+7
  html: ^0.15.0
  flutter_html: ^3.0.0-alpha.5
  modal_bottom_sheet: ^2.1.0
  flutter_hooks: ^0.20.3
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3+1
  path: ^1.8.2
  package_info_plus: ^4.1.0
  flutter_slidable: ^3.0.0
  envied: ^0.3.0
  sticky_headers: ^0.3.0+2
  app_common_flutter:
    git:
      url: https://github.com/huhx/app_common_flutter
      ref: main

dependency_overrides:
  modal_bottom_sheet:
   git:
     url: https://github.com/eli1stark/modal_bottom_sheet.git
     ref: main
     path: modal_bottom_sheet

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  retrofit_generator: ^8.0.0
  json_serializable: ^6.3.1
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.3.0
  build_runner: ^2.3.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/image/
    - assets/svg/
    - assets/sound/
    - assets/css/
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
